### ISSUE TITLE
Problem in visualizing generated model

### ISSUE THREAD

**Issue by jwut** [StanfordHCI/termite#20]
Hi all,

I imported one file with one passage per line and runed LDA modeling. I can get the trained LDA model, but cannot visualize the result. 

The data format is like this:
   01 [tab] xxx xxx

This is part of the output:
## Extracting topic model outputs: [data/esoap/lda] --> [data/esoap/entry-0000]

Importing a Mallet model...
    model = data/esoap/lda
    output = data/esoap/entry-0000
    min_term_freq = 20
    min_term_count = 5
Reading "topic-word-weights.txt" from Mallet...
## Writing data to disk...

Creating default index file: /index.json
Creating default state file: data/esoap/entry-0000/states.json

To give more clue, the index.json file has the content:
     { "runID" : "$RUN_IDENTIFIER", "entryIDs" : [ 0 ], "nextEntryID" : 1 }
while states.json file has nothing but a pair of empty bracket.

Someone successfully run the visualization? Please help!

Cheers!

**Comment by jcchuang** [comment]
That looks like the development/research branch.  As the name suggested, it's under development and won't work by just plugging a dataset.  You might want to use the master/release version instead.

**Comment by jcchuang** [comment]
Both files look correct.  Have you launched the web server?  What do you see in the browser?

**Comment by jwut** [comment]
Actually it is not the development/research branch. 
I can see the identifier of dataset from the browser, that's it. Nothing else.

**Comment by jcchuang** [comment]
Yikes! Looks like the master branch got corrupted. I've rolled it back to the correct commit. Let me know if the master branch works for you.  Version 1.1 in the master branch requires more setup though.  i.e., you need to create a configuration file prior to building a topic model.

I've remove the config file and streamlined model training in the upcoming version 2.  So, if you prefer to test the development branch:  I took a look and fixed a bug in the import script (which erroneously tries to save "index.json" to the root folder instead of inside the dataset folder).  The visualization should import and load properly now.

**Comment by jwut** [comment]
Thanks a lot. The development branch works. Great job!
