### ISSUE TITLE
Bug with empty string term?

### ISSUE THREAD

**Issue by arnicas** [StanfordHCI/termite#25]
Hi folks,
I've tried this out and get an error with an empty string term.  It looks like the parser is not filtering out u'' from the term lists.  In the mallet case, I can work around it, but the stanford topic modeler seems to be more likely to find only empty strings and fails totally - no topic terms output at all. If you want the file I input, I can send it if you email me. (It's tab sep txt.)

Good work though...
Lynn

**Comment by jcchuang** [comment]
Hi Lynn,

Thanks for the bug report. I've since moved the development efforts into two separate projects, [Termite Data Server](http://github.com/uwdata/termite-data-server) and [Termite Visualizations](http://github.com/uwdata/termite-visualizations), and so am no longer maintaining this repository. Please see if the other projects work for you.

Thanks for checking out Termite!
- Jason
